/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame2.java
 *
 * Created on Oct 1, 2011, 10:44:04 PM
 */
package com.masasdani.swingmakeover.paint;

/**
 *
 * @author home
 */
public class Frame2 extends javax.swing.JFrame {

    /** Creates new form Frame2 */
    public Frame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWarna1 = new com.masasdani.swingmakeover.paint.PanelWarna();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelWarna1Layout = new javax.swing.GroupLayout(panelWarna1);
        panelWarna1.setLayout(panelWarna1Layout);
        panelWarna1Layout.setHorizontalGroup(
            panelWarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        panelWarna1Layout.setVerticalGroup(
            panelWarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        getContentPane().add(panelWarna1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.masasdani.swingmakeover.paint.PanelWarna panelWarna1;
    // End of variables declaration//GEN-END:variables
}
