/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame4.java
 *
 * Created on Oct 1, 2011, 11:24:51 PM
 */
package com.masasdani.swingmakeover.button;

/**
 *
 * @author home
 */
public class Frame4 extends javax.swing.JFrame {

    /** Creates new form Frame4 */
    public Frame4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new com.masasdani.swingmakeover.panel.PanelImage();
        buttonEfek1 = new com.masasdani.swingmakeover.button.ButtonEfek();
        buttonEfek2 = new com.masasdani.swingmakeover.button.ButtonEfek();
        buttonEfek3 = new com.masasdani.swingmakeover.button.ButtonEfek();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonEfek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/masasdani/swingmakeover/draw/icon.png"))); // NOI18N
        buttonEfek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEfek1ActionPerformed(evt);
            }
        });

        buttonEfek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/masasdani/swingmakeover/draw/icon.png"))); // NOI18N
        buttonEfek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEfek2ActionPerformed(evt);
            }
        });

        buttonEfek3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/masasdani/swingmakeover/draw/icon.png"))); // NOI18N
        buttonEfek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEfek3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEfek1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEfek2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEfek3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEfek3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEfek2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEfek1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEfek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEfek1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_buttonEfek1ActionPerformed

    private void buttonEfek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEfek2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEfek2ActionPerformed

    private void buttonEfek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEfek3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEfek3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.masasdani.swingmakeover.button.ButtonEfek buttonEfek1;
    private com.masasdani.swingmakeover.button.ButtonEfek buttonEfek2;
    private com.masasdani.swingmakeover.button.ButtonEfek buttonEfek3;
    private com.masasdani.swingmakeover.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
